name: Actualizar resultados

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

  env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Buscar resultados si toca
        run: python actualizar_programado.py

      - name: Guardar cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizar resultados de loteria"
          file_pattern: resultados.json historicos/*.json
